"""
Retrieval Agent — hybrid search, answer generation, and citation formatting.

Design (from references/retrieval.md):
- Uses hybrid_search (dense + BM25 + reranking) from vector_store.
- Citations are extracted from chunk metadata post-generation, never re-generated by LLM.
- Optionally rewrites vague follow-up queries using conversation context.
"""
from __future__ import annotations

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from backend.core.llm_provider import extract_text, get_chat_llm

from backend.agents.state import GraphState
from backend.core.config import settings
from backend.core.logger import get_logger
from backend.ingestion.vector_store import hybrid_search

logger = get_logger(__name__)

_SYSTEM_PROMPT = """\
You are a financial document analyst. Answer the user's question based ONLY on the provided document excerpts.
Rules:
- Answer concisely and directly.
- If the answer is not in the provided context, say "I could not find this information in the document."
- Do NOT invent numbers or facts not present in the context.
- Do NOT include citation markers in your answer text — citations will be appended separately.
"""


def _format_citations(chunks: list[dict]) -> str:
    """Build a citation block from chunk metadata — never from LLM output."""
    seen: set[tuple] = set()
    citations = []
    for chunk in chunks:
        page = chunk.get("page_number")
        title = chunk.get("section_title", "")
        key = (page, title)
        if key not in seen:
            seen.add(key)
            citations.append(f"Page {page}" + (f" — {title}" if title else ""))
    return "**Sources:** " + " | ".join(citations) if citations else ""


def _maybe_rewrite_query(state: GraphState, query: str) -> str:
    """
    Rewrite vague pronoun-heavy follow-ups into specific retrievable queries.
    Only invoked when the query contains follow-up signals (short + pronouns).
    """
    follow_up_signals = {"it", "this", "that", "they", "them", "last year", "previous", "prior"}
    words = query.lower().split()
    if len(words) > 6 or not any(w in follow_up_signals for w in words):
        return query  # specific enough — skip rewrite

    # Build context from last 2 turns
    history_turns = []
    for msg in state["messages"][-4:]:
        role = "User" if isinstance(msg, HumanMessage) else "Assistant"
        history_turns.append(f"{role}: {extract_text(msg.content)[:200]}")
    history = "\n".join(history_turns)

    rewrite_prompt = (
        f"Given this conversation history:\n{history}\n\n"
        f"Rewrite this vague follow-up as a specific, self-contained search query about a financial document:\n"
        f"'{query}'\n\nRewritten query (one line only):"
    )
    llm = get_chat_llm(temperature=0, max_tokens=60)
    try:
        result = llm.invoke([HumanMessage(content=rewrite_prompt)])
        rewritten = extract_text(result.content).strip().strip('"').strip("'")
        logger.info("query_rewritten", extra={"original": query, "rewritten": rewritten})
        return rewritten
    except Exception as exc:
        logger.warning("query_rewrite_failed", extra={"error": str(exc)})
        return query


def retrieve_and_answer(state: GraphState) -> GraphState:
    """Retrieval Agent node — search, generate answer, append citations."""
    doc_id = state["doc_id"]
    last_message = state["messages"][-1]
    raw_query = extract_text(last_message.content) if hasattr(last_message, "content") else str(last_message)

    query = _maybe_rewrite_query(state, raw_query)

    try:
        chunks = hybrid_search(
            query,
            doc_id,
            k=settings.retrieval_top_k,
            rerank_top_n=settings.retrieval_rerank_top_n,
        )
    except Exception as exc:
        logger.error("retrieval_failed", extra={"error": str(exc)})
        return {**state, "error": f"Retrieval failed: {exc}"}

    if not chunks:
        no_context_msg = AIMessage(
            content="I could not find relevant information in the document for your question."
        )
        return {**state, "messages": [no_context_msg], "retrieved_context": [], "error": None}

    # Build context string for LLM
    context_parts = []
    for i, chunk in enumerate(chunks):
        page = chunk.get("page_number", "?")
        title = chunk.get("section_title", "")
        context_parts.append(f"[Excerpt {i+1} | Page {page} | {title}]\n{chunk['text']}")
    context_str = "\n\n---\n\n".join(context_parts)

    llm = get_chat_llm(temperature=0.1)

    try:
        response = llm.invoke([
            SystemMessage(content=_SYSTEM_PROMPT),
            HumanMessage(content=f"Document context:\n{context_str}\n\nQuestion: {raw_query}"),
        ])
        answer = extract_text(response.content).strip()
    except Exception as exc:
        logger.error("llm_generation_failed", extra={"error": str(exc)})
        return {**state, "error": f"Answer generation failed: {exc}"}

    # Append citations from metadata — never from LLM output
    citations = _format_citations(chunks)
    full_answer = f"{answer}\n\n{citations}" if citations else answer

    logger.info(
        "retrieval_answer_generated",
        extra={
            "doc_id": doc_id,
            "chunks_used": len(chunks),
            "query_preview": query[:80],
        },
    )

    return {
        **state,
        "messages": [AIMessage(content=full_answer)],
        "retrieved_context": chunks,
        "error": None,
    }
